# Generated by Django 4.2 on 2025-10-27 20:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="User's profile picture",
                max_length=255,
                null=True,
                verbose_name="profile_picture",
            ),
        ),
    ]
