# Generated by Django 5.2.7 on 2025-12-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (5, "5. Sınıf"),
                    (6, "6. Sınıf"),
                    (7, "7. Sınıf"),
                    (8, "8. Sınıf"),
                    (9, "9. Sınıf"),
                    (10, "10. Sınıf"),
                    (11, "11. Sınıf"),
                    (12, "12. Sınıf"),
                    (13, "Mezun"),
                ],
                help_text="Student's current grade (5-12) or Mezun",
                null=True,
                verbose_name="Grade",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lgs", "LGS"),
                    ("sayisal", "Sayısal"),
                    ("sozel", "Sözel"),
                    ("dil", "Dil"),
                ],
                help_text="Academic track (LGS, Sayısal, Sözel, Dil)",
                max_length=10,
                null=True,
                verbose_name="Track",
            ),
        ),
    ]
